# Section I - Regression analysis
## Data visualisation and descriptive measures
**Problem:** Zagat's publishes restaurant ratings for various locations in the United States. The CSV file contains the Zagat rating for food, decor, service, and the cost per person for a sample of 100 restaurants located in New York City and in a suburb of New York City. Develop a regression model to predict the cost per person, based on a variable that repersents the sum of the ratings for food, decor, and serivice

In [1]:
import Pkg

In [2]:
Pkg.add("CSV")

    Updating registry at `C:\Users\86865\.julia\registries\General`
    Updating git-repo `https://github.com/JuliaRegistries/General.git`
   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [3]:
Pkg.add("DataFrames")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [4]:
Pkg.add("Plots")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [5]:
Pkg.add("Lathe")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [6]:
Pkg.add("GLM")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [7]:
Pkg.add("StatsPlots")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [8]:
Pkg.add("MLBase")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [9]:
Pkg.add("LsqFit")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [10]:
using CSV

In [11]:
using DataFrames

In [12]:
using Plots

In [13]:
using Lathe

In [14]:
using GLM

In [15]:
using Statistics

In [16]:
using StatsPlots

In [17]:
using MLBase

In [18]:
using LsqFit

## Part A: Find the five point summary for summated rating and cost and then create a boxplot

In [136]:
# Read data from the csv file
data = CSV.read("Restaurant.CSV", DataFrame)

100×5 DataFrame
 Row │ Food   Decor  Service  Summated Rating  Cost  
     │ Int64  Int64  Int64    Int64            Int64 
─────┼───────────────────────────────────────────────
   1 │    22     14       19               55     33
   2 │    20     15       20               55     26
   3 │    23     19       21               63     43
   4 │    19     18       18               55     32
   5 │    24     16       18               58     44
   6 │    22     22       21               65     44
   7 │    22     20       20               62     50
   8 │    20     19       19               58     42
   9 │    21     17       19               57     44
  10 │    20     18       18               56     36
  11 │    23     22       24               69     61
  ⋮  │   ⋮      ⋮       ⋮            ⋮           ⋮
  91 │    26     17       24               67     49
  92 │    22     22       19               63     29
  93 │    24     18       22               64     33
  94 │    20     19       20               59     39
  95 │    26     19       23               68     39
  96 │    22     15       21               58     28
  97 │    18     20       18               56     46
  98 │    26     27       25               78     70
  99 │    25     26       23               74     60
 100 │    22     25       22               69     52
                                      79 rows omitted

In [137]:
# Provides the basic descriptive measures of the data
describe(data)

5×7 DataFrame
 Row │ variable         mean     min    median   max    nmissing  eltype   
     │ Symbol           Float64  Int64  Float64  Int64  Int64     DataType 
─────┼─────────────────────────────────────────────────────────────────────
   1 │ Food               22.42     18     22.0     27         0  Int64
   2 │ Decor              19.11     11     19.0     27         0  Int64
   3 │ Service            21.04     16     21.0     27         0  Int64
   4 │ Summated Rating    62.57     49     63.0     78         0  Int64
   5 │ Cost               46.85     25     44.0     80         0  Int64

In [138]:
# Store the specific column of the data file to be called later
cost = data[!, "Cost"]

100-element Vector{Int64}:
 33
 26
 43
 32
 44
 44
 50
 42
 44
 36
 61
 50
 51
  ⋮
 67
 68
 49
 29
 33
 39
 39
 28
 46
 70
 60
 52

In [139]:
ratings = data[!, "Summated Rating"]

100-element Vector{Int64}:
 55
 55
 63
 55
 58
 65
 62
 58
 57
 56
 69
 59
 61
  ⋮
 72
 70
 67
 63
 64
 59
 68
 58
 56
 78
 74
 69

In [23]:
# The following find out the five point summary for cost and ratings
y_min = minimum(cost)

25

In [24]:
y_max = maximum(cost)

80

In [25]:
y_q1 = quantile!(cost, 0.25)

36.0

In [26]:
y_q3 = quantile!(cost, 0.75)

54.25

In [27]:
y_median = median!(cost)

44.0

In [28]:
x_min = minimum(ratings)

49

In [29]:
x_max = maximum(ratings)

78

In [30]:
x_q1 = quantile!(ratings, 0.25)

57.0

In [31]:
x_q3 = quantile!(ratings, 0.75)

67.0

In [32]:
x_median = median!(ratings)

63.0

In [33]:
println("The five point summary for costs is $y_min, $y_q1, $y_median, $y_q3, $y_max")
println("The five point summary for ratings is $x_min, $x_q1, $x_median, $x_q3, $x_max")

The five point summary for costs is 25, 36.0, 44.0, 54.25, 80
The five point summary for ratings is 49, 57.0, 63.0, 67.0, 78


In [34]:
# This is the plotlyjs backends which allows the graph to show coordinates
plotlyjs()

HTML{String}("<script>\n// Immediately-invoked-function-expression to avoid global variables.\n(function() {\n    var warning_div = document.getElementById(\"webio-warning-16571047545680184628\");\n    var hide = function () {\n        var script = document.getElementById(\"webio-setup-11231192010666364769\");\n        var parent = script && script.parentElement;\n        var grandparent = parent && parent.parentElement;\n        if (grandparent) {\n            grandparent.style.display = \"none\";\n        }\n        warning_div.style.display = \"none\";\n    };\n    if (typeof Jupyter !== \"undefined\") {\n        console.log(\"WebIO detected Jupyter notebook environment.\");\n        // Jupyter notebook.\n        var extensions = (\n            Jupyter\n            && Jupyter.notebook.config.data\n            && Jupyter.notebook.config.data.load_extensions\n        );\n        if (extensions && extensions[\"webio-jupyter-notebook\"]) {\n            // Extension already loaded.\n            console.log(\"Jupyter WebIO nbextension detected; not loading ad-hoc.\");\n            hide();\n            return;\n        }\n    } else if (window.location.pathname.includes(\"/lab\")) {\n        // Guessing JupyterLa\n        console.log(\"Jupyter Lab detected; make sure the @webio/jupyter-lab-provider labextension is installed.\");\n        hide();\n        return;\n    }\n})();\n\n</script>\n<p\n    id=\"webio-warning-16571047545680184628\"\n    class=\"output_text output_stderr\"\n    style=\"padding: 1em; font-weight: bold;\"\n>\n    Unable to load WebIO. Please make sure WebIO works for your Jupyter client.\n    For troubleshooting, please see <a href=\"https://juliagizmos.github.io/WebIO.jl/latest/providers/ijulia/\">\n    the WebIO/IJulia documentation</a>.\n    <!-- TODO: link to installation docs. -->\n</p>\n")

Plots.PlotlyJSBackend()

In [142]:
# boxplot for ratings which shows the five point summary 
boxplot(ratings, title = "Box Plot - Restaurant ratings", ylabel = "Ratings")

<!DOCTYPE html>
 
 
 Plots.jl

In [36]:
# boxplot for costs which shows five point summary
boxplot(cost, title = "Box Plot - Restaurant Costs", ylabel = "Costs")

<!DOCTYPE html>
 
 
 Plots.jl

## Part B: Construct a scatter plot with summated ratings being x and cost of meal being y

In [37]:
# to showcase the name of each data set contained in the file
names(data)

5-element Vector{String}:
 "Food "
 "Decor"
 "Service"
 "Summated Rating"
 "Cost"

In [143]:
# Draw a scatter plot with labels
scatter(ratings, cost, label = "Points")
xlabel!("summated ratings")
ylabel!("cost of meal")
title!("Restaurant research")

<!DOCTYPE html>
 
 
 Plots.jl

## Part C: Find and comment on the correlation coefficient and coefficient of determination for ratings and costs

In [39]:
# Find out the correlation of the two variables
correl = cor(ratings, cost)
println("Correlation of summated ratings with cost of meal is $correl")
println("This show us that there is a strong positive relationship between the summated ratings and cost")

Correlation of summated ratings with cost of meal is 0.932192459558199
This show us that there is a strong positive relationship between the summated ratings and cost


In [144]:
# Define a new list that only contain these two variables
df = DataFrame(new_ratings = ratings, new_cost = cost)

100×2 DataFrame
 Row │ new_ratings  new_cost 
     │ Int64        Int64    
─────┼───────────────────────
   1 │          55        33
   2 │          55        26
   3 │          63        43
   4 │          55        32
   5 │          58        44
   6 │          65        44
   7 │          62        50
   8 │          58        42
   9 │          57        44
  10 │          56        36
  11 │          69        61
  ⋮  │      ⋮          ⋮
  91 │          67        49
  92 │          63        29
  93 │          64        33
  94 │          59        39
  95 │          68        39
  96 │          58        28
  97 │          56        46
  98 │          78        70
  99 │          74        60
 100 │          69        52
              79 rows omitted

In [145]:
# To find out the coefficient of determination, we can create the regression table
fm = @formula(new_cost~new_ratings)
linearRegressor = lm(fm, df)

StatsModels.TableRegressionModel{LinearModel{GLM.LmResp{Vector{Float64}}, GLM.DensePredChol{Float64, CholeskyPivoted{Float64, Matrix{Float64}}}}, Matrix{Float64}}

new_cost ~ 1 + new_ratings

Coefficients:
─────────────────────────────────────────────────────────────────────────
                 Coef.  Std. Error      t  Pr(>|t|)  Lower 95%  Upper 95%
─────────────────────────────────────────────────────────────────────────
(Intercept)  -46.7718     8.67463   -5.39    <1e-06  -63.9863   -29.5573
new_ratings    1.49627    0.137875  10.85    <1e-17    1.22266    1.76988
─────────────────────────────────────────────────────────────────────────

In [146]:
r_square = r2(linearRegressor)

0.5458223250942029

In [147]:
println("As coefficient of determination is $r_square , this show us that $(r_square*100) % of total variation in the cost of meal is explained by summated ratings")

As coefficient of determination is 0.5458223250942029 , this show us that 54.582232509420294 % of total variation in the cost of meal is explained by summated ratings


## Part D: Assuming a linear relationship, use the least-squares method to compute the regression coefficient beta 0 and beta 1. Then write down and plot the estimated regression equation.

In [148]:
# x is the rating, y is the cost
# The formula to find b1(slope variable) is covariance divide by the variance of x variable
covariance = cov(ratings, cost)

65.7530303030303

In [149]:
var_x = var(ratings)

43.944545454545455

In [150]:
# The formula to find b0(intercept) is the mean of y minus the mean of x times b1(slope variable)
x_bar = mean(ratings)

62.57

In [151]:
y_bar = mean(cost)

46.85

In [152]:
b1 = covariance/var_x

1.49627285076922

In [153]:
b0 = y_bar - b1*x_bar

-46.7717922726301

In [154]:
# This is the linear regression equation
println("The equation of the regression line for this model is $b0 + $b1 * x")

The equation of the regression line for this model is -46.7717922726301 + 1.49627285076922 * x


In [155]:
# the regression line must be in the same range as the original dataset
x = x_min:x_max 
f(x) = b0 + b1*x
y = f.(x)

30-element Vector{Float64}:
 26.54557741506168
 28.041850265830895
 29.538123116600126
 31.034395967369342
 32.53066881813856
 34.026941668907774
 35.523214519677005
 37.01948737044622
 38.51576022121544
 40.01203307198465
 41.508305922753884
 43.0045787735231
 44.500851624292316
  ⋮
 53.47848872890764
 54.97476157967686
 56.471034430446075
 57.967307281215305
 59.46358013198452
 60.95985298275374
 62.456125833522954
 63.952398684292184
 65.44867153506141
 66.94494438583061
 68.44121723659984
 69.93749008736907

In [156]:
# Plot the regression line with the scatter plot
plot(x, y, linestyle = [:dash], label = "regression line"); scatter!(ratings, cost, label="points")
xlabel!("Restaurant Rating")
ylabel!("Cost of meal")
title!("Restaurant Research")

<!DOCTYPE html>
 
 
 Plots.jl

┌ Warning: Indices Base.OneTo(1) of attribute `linestyle` does not match data indices 1:30.
└ @ Plots C:\Users\86865\.julia\packages\Plots\iYDwd\src\utils.jl:108
┌ Warning: Indices Base.OneTo(1) of attribute `linestyle` does not match data indices 1:30.
└ @ Plots C:\Users\86865\.julia\packages\Plots\iYDwd\src\utils.jl:108


## Part E: using the regression  model to predict the cost of meal for a restaurant that has a summated rating of 50.

In [157]:
# use the regression model to estimate the cost for the restaurant that has a rating of 50
x_cost = b0 + 50*b1

28.041850265830895

In [158]:
x_cost = round(x_cost, digits = 2)

28.04

In [159]:
println("The cost of meal for a restaurant that has a summated rating of 50 is estimated to be \$ $x_cost")

The cost of meal for a restaurant that has a summated rating of 50 is estimated to be $ 28.04


## Part F: Through graphing residual plots and histograms, prove whether the assumptions of linearity, independence of error, normality of error and equal variance are valid.

In [160]:
# Find the size of the dataset
size(df, 1)

100

In [161]:
# To find residuals, we need to compare the estimated cost with the actual cost
# Loop through all the actual cost and minus it by the estimated cost
array = []
for i in 1: size(df, 1)
    x_value = df[i, 1]
    y_value = df[i, 2]
    est_y = b0 + b1*x_value
    residual = y_value - est_y
    push!(array, residual)
end

In [162]:
# Using the data obtained above to plot a histogram
histogram(array, title = "Residual Graph", ylabel = "Frequency", xlabel = "residuals")

<!DOCTYPE html>
 
 
 Plots.jl

In [163]:
# Comment on the findings
println("From the graph we can see that the errors are not exactly normally distributed")
println("However, as the sample size is bigger than 30, CLT can apply")

From the graph we can see that the errors are not exactly normally distributed
However, as the sample size is bigger than 30, CLT can apply


In [164]:
using Plots

In [165]:
# Plot scatter plot with residuals on the y axis, ratings on the x axis
scatter(ratings,array, shape = :rect)
xlabel!("Ratings")
ylabel!("Residuals")
title!("Residual Plot")

<!DOCTYPE html>
 
 
 Plots.jl

In [166]:
# Comment on the findings of the graphs
println("From this residual plot we can see that there is no clear pattern presented, therefore the errors are likely to be independent")
println("The linearity, independence of error and homoscedasticity are not violated")

From this residual plot we can see that there is no clear pattern presented, therefore the errors are likely to be independent
The linearity, independence of error and homoscedasticity are not violated


In [167]:
println("As shown in the residual plot and the residual graph, the assumptions of regression is not violated")
println("Therefore, our previous conslusions are valid")

As shown in the residual plot and the residual graph, the assumptions of regression is not violated
Therefore, our previous conslusions are valid


# Section II: Risk Management
## Comparing financial risks and return
**Problem:** You plan to invest $1,000  in a corporate bond fund or in a common stock fund. The CSV file named "Stocks.csv" presents the annual return (per 1,000 dollar) of each investments under various economic conditions and the probability that each of those economic conditions will occur.

In [64]:
using CSV

In [65]:
using DataFrames

In [66]:
# Import csv file
stocks = CSV.read("Stocks.csv", DataFrame)

6×7 DataFrame
 Row │ Probability P(X=x, Y=y)  Economic Condition  Corporate Bond Fund (x)  C ⋯
     │ Float64                  String              Int64                    I ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │                    0.01  Extreme Recession                      -200    ⋯
   2 │                    0.09  Recession                               -70
   3 │                    0.15  Stagnation                               30
   4 │                    0.35  Slow growth                              80
   5 │                    0.3   Moderate growth                         100    ⋯
   6 │                    0.1   High growth                             120
                                                               4 columns omitted

In [67]:
println(stocks[1,1])

0.01


In [68]:
names(stocks)

7-element Vector{String}:
 "Probability P(X=x, Y=y)"
 "Economic Condition"
 "Corporate Bond Fund (x)"
 "Common Stock Fund (y)"
 "x^2"
 "y^2"
 "xy"

In [69]:
# Rename the columns for the convenience to call the dataset later on
rename!(stocks, "Probability P(X=x, Y=y)" => "Probability")
rename!(stocks, "Corporate Bond Fund (x)" => "Corporate Bond")
rename!(stocks, "Common Stock Fund (y)" => "Common Stock")

6×7 DataFrame
 Row │ Probability  Economic Condition  Corporate Bond  Common Stock  x^2    y ⋯
     │ Float64      String              Int64           Int64         Int64  I ⋯
─────┼──────────────────────────────────────────────────────────────────────────
   1 │        0.01  Extreme Recession             -200          -999  40000  9 ⋯
   2 │        0.09  Recession                      -70          -300   4900
   3 │        0.15  Stagnation                      30          -100    900
   4 │        0.35  Slow growth                     80           100   6400
   5 │        0.3   Moderate growth                100           150  10000    ⋯
   6 │        0.1   High growth                    120           350  14400  1
                                                               2 columns omitted

In [70]:
# Allocate the specific column to a variable
prob = stocks[!, "Probability"]
corporate = stocks[!, "Corporate Bond"]
common = stocks[!, "Common Stock"]

6-element Vector{Int64}:
 -999
 -300
 -100
  100
  150
  350

## Part A: Compute the expected return for the corporate bond fund and for the common stock fund

In [71]:
# Function to find the sum of the products of two lists
function sumproduct(x, y)
    total = 0
    for i in 1:length(x)
        total += x[i] * y[i]
    end
    return total
end

sumproduct (generic function with 1 method)

In [72]:
# The expected value is calculated through taking the sum of the product of the probability and the actual return of the investment
total = sumproduct(prob, corporate)
println("The expected return for Corporate bond fund is $total")

The expected return for Corporate bond fund is 66.2


In [73]:
total_2 = sumproduct(common, prob)
println("The expected return for Common stock fund is $total_2")

The expected return for Common stock fund is 63.01


## Part B: Compute the standard deviation for the corporate bond fund and for the common stock fund

In [74]:
# Function to find the square of each element in the list
function squared_list(list)
    squared = []
    for x in list
        y = x^2
        push!(squared, y)
    end
    return squared
end

squared_list (generic function with 1 method)

In [75]:
x_squared = squared_list(corporate)

6-element Vector{Any}:
 40000
  4900
   900
  6400
 10000
 14400

In [76]:
total_3 = sumproduct(x_squared, prob)

7656.0

In [77]:
# Standard deviation can be find through the square root of the E(x^2) - E(x)^2
stdev_1 = sqrt(total_3 - total^2)
stdev_1 = round(stdev_1, digits = 2)

57.22

In [78]:
println("The standard deviation for the corporate bond fund is $stdev_1")

The standard deviation for the corporate bond fund is 57.22


In [79]:
# To calculate the standard deviation we need to find the squared term of each element and its sumproduct with the probabilirt
# As well as the squared expected return
y_squared = squared_list(common)

6-element Vector{Any}:
 998001
  90000
  10000
  10000
  22500
 122500

In [80]:
total_4 = sumproduct(y_squared, prob)

42080.01

In [81]:
stdev_2 = sqrt(total_4 - total_2^2)
stdev_2 = round(stdev_2, digits = 2)

195.22

In [82]:
println("The standard deviation for the common stock fund is $stdev_2")

The standard deviation for the common stock fund is 195.22


## Part C: Find the covariance of the corporate bond and the common stock fund

In [83]:
# Loop through to have a list that contain all of the product of corporate fund and corresponding common stock's return of investment
new_list = []
for i in 1:length(corporate)
    value = corporate[i] * common[i]
    push!(new_list, value)
end
println(new_list)

Any[199800, 21000, -3000, 8000, 15000, 42000]


In [84]:
# Covariance is found through E(XY) - E(x)*E(y)
expected_xy = sumproduct(prob, new_list)

14938.0

In [85]:
ex_ey = total * total_2

4171.262

In [86]:
covariance = expected_xy - ex_ey
covariance = round(covariance, digits = 2)
println("The covariance is $covariance")

The covariance is 10766.74


## Part D: Would you invest in the corporate bond or the common stock fund? Explain.

In [87]:
# Find out which bond has better return on invesment
if total > total_2
    fund = "Corporate bond"
    ave_return = total
else
    fund = "Common stock"
    ave_return = total_2
end

66.2

In [88]:
# This function evaluates whether the bond with better return will have higher risk or lower risk
function standard(fund_name)
    if fund_name == "Corporate bond"
        sd = stdev_1
        if stdev_1 < stdev_2
            trend = "less variation"
            solution = "lower risks"
        else
            trend = "more variation"
            solution = "higher risks"
        end
    else
        sd = stdev_2
        if stdev_1 < stdev_2
            trend = "more variation"
            solution = "higher risks"
        else
            trend = "less variation"
            solution = "lower risks"
        end
    end
    return sd, trend, solution
end

answer = standard(fund)
sd = answer[1]
trend = answer[2]
solution = answer[3]
println("$fund is a better choice, as the average return is $ave_return which is relatively higher, it's standard deviation is $sd, which has $trend meaning $solution")

Corporate bond is a better choice, as the average return is 66.2 which is relatively higher, it's standard deviation is 57.22, which has less variation meaning lower risks


# Section III: Probability distribution
## Calculating probability of normal distribution
**Problem:** Past records for the population of internet users show that the amount of time each customer spends at internet cafe spending e-mails is distributed with a mean of 9 minutes and a standard deviation of 2.5.


## Part A: If a random sample of n = 30 is selected, what is the standard error of the sample mean?

In [89]:
# Standard error is calculated through mean divided by the square root of sample size
x_bar = 9
sd = 2.5
n = 30
se = x_bar/sqrt(n)
se = round(se, digits = 2)
println("Standard error is $se")

Standard error is 1.64


## Part B: What is the probability that a selected time is less than 7 minutes?

In [90]:
Pkg.add("Distributions")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [91]:
using Distributions

In [92]:
# using distributions package to find the probability of normally distributed function
dist = Normal(x_bar, sd)

Normal{Float64}(μ=9.0, σ=2.5)

In [93]:
probability = sum(cdf.(dist, collect(:7)))
probability = round(probability, digits = 2)
println("P(x < 7) = $probability")

P(x < 7) = 0.21


## Part C: If the sample mean was 10 minutes, calculate a 95% confidence interval for the mean. Does this interval include the true population mean?

In [94]:
using Statistics

In [95]:
# Find the z score through using the builtin function of Statistics of 95% confidence level
sample_mean = 10
z_stat = (sample_mean - x_bar)/sd
z_crit = quantile(Normal(), 1-(1-0.95)/2)

1.9599639845400576

In [96]:
# Interval can be found through x +/- z score * standard error
ucl = round(sample_mean + z_crit * se)
lcl = round(sample_mean - z_crit * se)

7.0

In [97]:
# Print result of the question
if x_bar in lcl:ucl
    println("The true population $x_bar is in the range of $ucl and $lcl")
else
    println("Not in range the range")
end

The true population 9 is in the range of 13.0 and 7.0


# Section IV: Quadratic Equation
## Finding the intersections of a quadratic equation and a linear equation

In [98]:
Pkg.add("NLsolve")

   Resolving package versions...
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Project.toml`
  No Changes to `C:\Users\86865\.julia\environments\v1.6\Manifest.toml`


In [99]:
using NLsolve

In [100]:
# Defining the function that needs to be solved
# Find the intersection of y = x^2 and y = -2(x-2) + 3
function f!(F, v)
    x = v[1]
    y = v[2]
    F[1] = -x^2 + y
    F[2] = 2*(x-2) + y - 3
end

f! (generic function with 1 method)

In [101]:
# As the two equations intersect, their x and y coordinates must be the same
# Therefore x1-x2 = 0, y1-y2 = 0
res = nlsolve(f!, [0.0; 0.0])

Results of Nonlinear Solver Algorithm
 * Algorithm: Trust-region with dogleg and autoscaling
 * Starting Point: [0.0, 0.0]
 * Zero: [1.8284271247462098, 3.3431457505075803]
 * Inf-norm of residuals: 0.000000
 * Iterations: 6
 * Convergence: true
   * |x - x'| < 0.0e+00: false
   * |f(x)| < 1.0e-08: true
 * Function Calls (f): 7
 * Jacobian Calls (df/dx): 7

In [102]:
# Coordinates of intersection
res.zero

2-element Vector{Float64}:
 1.8284271247462098
 3.3431457505075803

# Section V: Linear Equations
## Solving linear equations through using matrix factorisation 

In [103]:
# Generating a random 3x3 matrix
A = rand(1:5, 4, 4)

4×4 Matrix{Int64}:
 2  1  1  3
 5  2  5  2
 1  3  3  3
 5  1  1  3

In [104]:
# Creating a vector
x = fill(1.0, (4, ))

4-element Vector{Float64}:
 1.0
 1.0
 1.0
 1.0

In [105]:
# Defining a linear equation to be solved
b = A * x

4-element Vector{Float64}:
  7.0
 14.0
 10.0
 10.0

In [106]:
# Julia provides a convenient way to solve linear equation through "\"
# However, as the data is generated randomly, it may not always have a solution
A\b

4-element Vector{Float64}:
 1.0
 0.9999999999999997
 1.0000000000000002
 1.0

In [107]:
# Another way to solve linear equation is to use the LinearAlgebra package
using LinearAlgebra

In [108]:
# Generat some data to use for the linear equation
A = rand(4, 4)

4×4 Matrix{Float64}:
 0.319968   0.850625  0.715586  0.669067
 0.358051   0.536764  0.330574  0.612338
 0.507362   0.417624  0.234291  0.857741
 0.0987246  0.340671  0.725083  0.465611

In [109]:
# Creating a vector
x = fill(1, (4, ))

4-element Vector{Int64}:
 1
 1
 1
 1

In [110]:
# Define the linear equation
b = A*x

4-element Vector{Float64}:
 2.555246054049749
 1.837727012851401
 2.0170187531576884
 1.630089965460172

In [111]:
# Factorise the matrix to solve the equation to speed up problem
# Factorisation object that contains the matrix of L and U
Alu = lu(A)

LU{Float64, Matrix{Float64}}
L factor:
4×4 Matrix{Float64}:
 1.0       0.0        0.0       0.0
 0.63065   1.0        0.0       0.0
 0.194584  0.441734   1.0       0.0
 0.705711  0.412161  -0.160512  1.0
U factor:
4×4 Matrix{Float64}:
 0.507362  0.417624  0.234291   0.857741
 0.0       0.58725   0.567831   0.128132
 0.0       0.0       0.428664   0.242108
 0.0       0.0       0.0       -0.0069293

In [112]:
# To obtain the permutation matrix
Alu.P

4×4 Matrix{Float64}:
 0.0  0.0  1.0  0.0
 1.0  0.0  0.0  0.0
 0.0  0.0  0.0  1.0
 0.0  1.0  0.0  0.0

In [113]:
# To obatin the lower triangular matrix
Alu.L

4×4 Matrix{Float64}:
 1.0       0.0        0.0       0.0
 0.63065   1.0        0.0       0.0
 0.194584  0.441734   1.0       0.0
 0.705711  0.412161  -0.160512  1.0

In [114]:
# To obtain the upper triangular matrix
Alu.U

4×4 Matrix{Float64}:
 0.507362  0.417624  0.234291   0.857741
 0.0       0.58725   0.567831   0.128132
 0.0       0.0       0.428664   0.242108
 0.0       0.0       0.0       -0.0069293

In [115]:
A\b

4-element Vector{Float64}:
 1.0000000000000377
 0.999999999999992
 1.0000000000000127
 0.999999999999978

In [116]:
# As it is shown, both way provides the same output
Alu\b

4-element Vector{Float64}:
 1.0000000000000377
 0.999999999999992
 1.0000000000000127
 0.999999999999978

# Section VI: Matrix
## Dictionaries and matrix
**Problem:** user input the degree, as well as the coefficient for x and the constant variable for a polynomial equation (ax+b)^n. The program then expand this binomial distribution, the kth term's coefficient is given as an output

In [117]:
# Print out the standard formula
println("To expand the polynomial (ax + b)^ n")
# Ask for user's input for the degree
println("Please enter an integer for the degree of the polynomial! (n)")
n = readline()

To expand the polynomial (ax + b)^ n
Please enter an integer for the degree of the polynomial! (n)
stdin> 3


"3"

In [118]:
# Loop through the question until user give an integer is provided
while (tryparse(Int64, n) !== nothing) == false
    println("Input an integer for n!")
    global n = readline()
end

In [119]:
n = parse(Int64, n)
# Since the equation is a polynomial, the degree has to be greater than 1
# The command is repeated until a valid answer is provided
while n < 2
    println("Please enter an integer greater than 1")
    global n = readline()
    n = parse(Int64, n)
end

In [120]:
# Asking user to input a coefficient for the x 
println("Please enter an integer for the coefficient of x! (a)")
a = readline()

# Loop through until an integer is provided
while (tryparse(Int64, a) !== nothing) == false
    println("Input an integer for a!")
    global a = readline()
end

Please enter an integer for the coefficient of x! (a)
stdin> 2


In [121]:
# Asking user to input a constant 
println("Please enter an integer for the constant variable! (b)")
b = readline()

# Loop through the question until a valid input is provided
while (tryparse(Int64, b) !== nothing) == false
    println("Input an integer for b!")
    global b = readline()
end

Please enter an integer for the constant variable! (b)
stdin> 4


In [122]:
# Print out the equation that user input
println("The polynomial is ($a * x + $b) ^ $n")

The polynomial is (2 * x + 4) ^ 3


In [123]:
# Convert the inputs into integers
b = parse(Int64, b)
a = parse(Int64, a)
# creating a 2D matrix to store the values
lst = zeros(Int64, n + 1, n + 1)

4×4 Matrix{Int64}:
 0  0  0  0
 0  0  0  0
 0  0  0  0
 0  0  0  0

In [124]:
# The following calculate the result of combinations eg. 3C0 = 1
for y in 1 : n + 1
    for x in 1 : n + 1
        # The sides of the matrix all contain a value of 1
        if (x == 1) | (y == 1)
            lst[x, y] = 1
        # In combination, nCk = (n-1)Ck + (n-1)C(k-1)
        # In this case, since all the values are stored in a square, rather than a triangle
        # The new equation would be nCk = (n-1)Ck + nC(k-1)
        else
            lst[x, y] = lst[x-1, y] + lst[x, y-1]
        end

    end
end

In [125]:
# The matrix showing combination values
println(lst)

# An empty dictionary to store each coefficient
empty_dict = Dict()

# The following aim to find coefficient of different terms
for i in 1 : n + 1
    # The combination value can be find through identifying the diagonal values of the matrix
    num = lst[i, n-i+2] 
    # The actual coefficient can be find through nCk * a^n * b^(n-k)
    # However, as i is one bigger than n, we need to subtract 1 from i to calculate the correct result
    new_b = b ^ (i-1)
    new_a = a ^ (n-i+1)
    product = new_a * new_b * num 
    println("The coefficient of x^$(n-i+1) is $product")
    # Each coefficient is stored with the actual term
    empty_dict["x^$(n-i+1)"] = string(product)
end

[1 1 1 1; 1 2 3 4; 1 3 6 10; 1 4 10 20]
The coefficient of x^3 is 8
The coefficient of x^2 is 48
The coefficient of x^1 is 96
The coefficient of x^0 is 64


In [126]:
# Asking user to input the k th term in which they wish to find the coefficient
println("To find a specific coefficient of k th term, please input an integer for k!")
k = readline()
# The question is looped until an integer is given
while (tryparse(Int64, k) !== nothing) == false
    println("Input an integer for k!")
    global k = readline()
end

To find a specific coefficient of k th term, please input an integer for k!
stdin> 3


In [127]:
k = parse(Int64, k)

# The value of k is limited to the number of terms within the expansion of the binomial
# Thus if k is smaller than 0 or bigger than the number of terms, it cannot be accepted
value = false
while value == false
    if k < 0
        println("Please enter an integer greater than or equal to 1")
        global k = readline()
        k = parse(Int64, k)
    
    elseif k > n+1
        println("There is only $(n+1) terms in this equation, please enter an integer smaller or equal to $(n+1)")
        global k = readline()
        k = parse(Int64, k)

    else
        global value = true
        break
    end
end

In [128]:
# Print out the final answer
answer = empty_dict["x^$(n-k+1)"]
println("The coefficient for $k th term is $answer")

The coefficient for 3 th term is 96
